### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by mcaulifn** [jtyr/yaml2toml-converter#1]
Hey I'm trying to use this to render a telegraf config. I'm running in to some issues.

```
telegraf_custom_plugins_extra:
  switches:
    inputs.snmp:
      agents:
        - 172.16.1.0
        - 172.16.1.6
        - 172.16.0.30
      version: 2
      community: publiv
      name: system
      field:
        - name: hostname
          oid: .1.3.6.1.2.1.1.5.0
          is_tag: true
        - name: uptime
          oid: .1.3.6.1.2.1.1.3.0
        - name: sysObjectID
          oid: .1.3.6.1.2.1.1.2.0
      table:
        - name: interface_stats
          inherit_tags:
            - hostname
          field:
            - name: ifName
              oid: .1.3.6.1.2.1.31.1.1.1.1
              is_tag: true
      tags:
          deviceType: switch
          customer: me
```
gets me:
```
[inputs.snmp]
agents = ['172.16.1.0', '172.16.1.6', '172.16.0.30']
community = "publiv"
name = "system"
version = 2

  [[inputs.snmp.field]]
  is_tag = True
  name = "hostname"
  oid = ".1.3.6.1.2.1.1.5.0"

  [[inputs.snmp.field]]
  name = "uptime"
  oid = ".1.3.6.1.2.1.1.3.0"

  [[inputs.snmp.field]]
  name = "sysObjectID"
  oid = ".1.3.6.1.2.1.1.2.0"

  [[inputs.snmp.table]]
  inherit_tags = ['hostname']
  name = "interface_stats"

    [[field]]
    is_tag = True
    name = "ifName"
    oid = ".1.3.6.1.2.1.31.1.1.1.1"

  [inputs.snmp.tags]
  customer = "me"
  deviceType = "switch"
```

The `True`s should be `true` and the `[[field]]` should be `[[inputs.snmp.table.field]]`.

Any suggestions?
